### ISSUE TITLE
imu data is not proper using ros

### ISSUE THREAD

**Issue by Neel125** [econsystems/taraxl-ros-package#1]
Hello, 
I was installed Taraxl SDK in xavier and then after i installed taraxl-ros-package. All topics were work correctly but following imu topic always gives same values like all 0 s.
```
rostopic echo /taraxl/imu/data_raw
```
```
---
header: 
  seq: 153468
  stamp: 
    secs: 1602235463
    nsecs: 133998392
  frame_id: "taraxl_IMU"
orientation: 
  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0
orientation_covariance: [-1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.0
  y: 0.0
  z: 0.0
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
```

and also using below command 

`rostopic echo /taraxl/imu/inclination `

i got below values 

```
---
x: 0.0
y: 0.0
z: 0.0
---

```

but after that i run taraxl-imu-viewer of taraxl-tools and it gives me some better values like below image,  not like all 0 s using ros gave me.

![Screenshot from 2020-10-09 14-49-49](https://user-images.githubusercontent.com/39521135/95566087-ba03e680-0a3e-11eb-831e-1e75c4c554a3.png)

so what am i doing wrong ? or How can i get proper data using SDK ?
please help me.
